facebook/react-strict-dom

- packages/react-strict-dom/README.md
If anyone would like to read the package README on `npm` directly, pressing on `COMPATIBILITY` will return **404**
> Fix link to `compatibility.md`

- apps/examples/src/App.js
- packages/eslint-plugin/src/valid-styles.js
- packages/react-strict-dom/COMPATIBILITY.md
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
- packages/react-strict-dom/tests/css-test.native.js
- packages/react-strict-dom/tests/html-test.native.js
Implements a partial polyfill for non-inheritable 'visibility'. This does not polyfill the web behavior of being able to selectively override the 'visibility' of elements nested within an element with 'visibility:hidden'.
As result, this patch also removes 'visibility' from the inheritable text styles. Originally visibility was added here simply because it is considered an inheritable property on web, even though we didn't do anything with the property on native. In the context of these polyfills, we're only interested in being able to inherit text styles and cannot do anything with inherited visibility, so there is no functional change to the existing polyfill for inheritable text styles.
Also note that no attempt is made to implement 'collapse' as per W3C spec, as this behavior does not …
> Partial polyfill for CSS 'visibility'

- configs/jest-dom-resolver.js
- configs/jest-native-resolver.js
I reported the issue in https://github.com/facebook/react-strict-dom/issues/46
There was an issue with tests not running in the "Windows" environment.
"posix" may be removed unless there is a specific reason for it to only be included in "testPathForConsistencyCheck".
If there is a reason, please let me know.
> Fix custom snapshot resolver consistency

- apps/examples/src/App.js
- packages/react-strict-dom/src/dom/html.js
- packages/react-strict-dom/src/dom/runtime.js
- packages/react-strict-dom/src/native/html.js
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-dom
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-native
- packages/react-strict-dom/tests/html-test.js
Adds support for `del`, `ins`, `kbd`, `s`, and `u` semantic elements to web and native.
iOS rendering:
> Add 'del', 'ins', 'kbd', 's', 'u' semantic elements

- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/tests/html-test.native.js
React Native's "Fabric" architecture appears to have a bug and does not populate the Image 'load' event with 'source' data.
> Fix html.img event bug in Fabric

- configs/rollup.config.js
- packages/react-strict-dom/COMPATIBILITY.md
- packages/react-strict-dom/src/dom/modules/ThemeContext.js
Internally we could use patch files to rewrite the stylex import on web, and add the comment directives to exclude the files from linting/formatting, etc.
> Remove rollup configs for internal builds

- packages/react-strict-dom/README.md
- packages/react-strict-dom/src/dom/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/useStyleTransition.js
- packages/react-strict-dom/src/native/stylex/customProperties.js
- packages/react-strict-dom/src/native/stylex/fixContentBox.js
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/tests/css-test.native.js
Improve the DX of using LogBox suppression in React Native by using a common structure for error/warn messages. This allows for easier configuration to suppress either specific messages, or categories of messages, e.g., "all unsupported properties" or "all unsupported values".
> Provide structured error/warn messages

- packages/react-strict-dom/src/types/StrictReactDOMAnchorProps.js
- packages/react-strict-dom/src/types/StrictReactDOMButtonProps.js
- packages/react-strict-dom/src/types/StrictReactDOMImageProps.js
- packages/react-strict-dom/src/types/StrictReactDOMInputProps.js
- packages/react-strict-dom/src/types/StrictReactDOMOptionGroupProps.js
- packages/react-strict-dom/src/types/StrictReactDOMOptionProps.js
- packages/react-strict-dom/src/types/StrictReactDOMProps.js
- packages/react-strict-dom/src/types/StrictReactDOMSelectProps.js
- packages/react-strict-dom/src/types/StrictReactDOMTextAreaProps.js
Allow `null` or `undefined` values in most cases.
Allows for code like this, where `props.role` might be undefined:
```jsx
<html.div role={props.role} />
```
This works with React DOM, because the props are any-typed.
> Relax the Flow types for props

- packages/react-strict-dom/src/native/stylex/CSSTextShadow.js
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/src/native/stylex/parseShadow.js
Only transform CSS textShadow into React Native textShadow styles during the style resolving pass. Minor clean up to reduce how much of this kind of work is done in style pre-processing rather than style resolving.
> Avoid non-standard textShadow in preprocessing step

- apps/examples/src/App.js
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
- packages/react-strict-dom/tests/css-test.native.js
- packages/react-strict-dom/tests/html-test.native.js
When a unitless lineHeight is inherited, it multiples the value of the fontSize of the inheriting element. But when an em value is inherited, it multiples the value of the fontSize of the element it was originally applied to, not the one on the inheriting element.
This patch fixes the resolved values to match web's computed values, but React Native itself renders line-height differently from web, as you can see in these screenshots. Text elements have a semi-transparent red background. React Native changes the shape of the text element box when the line box size changes, and the line box of the parent text seems to grow to match the largest nested line box.
**Web**
**Native**
> Fix polyfill for unitless lineHeight

- packages/react-strict-dom/src/native/stylex/CSSLengthUnitValue.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/css-test.native.js
Add parsing for signage in string length unit values:
- Adding parsing for (+/-) signs
- Multiplying parsed float by -1 if sign = "-"
- Updated tests and snapshots
Modifying tests to account for positive and negative signs 
Ran `npm run jest /packages/react-strict-dom/tests/css-test.native.js`
> Adding regex handling for negative signs

- .github/workflows/performance.yml
- .github/workflows/react-integration.yml
- .github/workflows/tests.yml
- .gitignore
- CONTRIBUTING.md
- configs/.eslintrc
- configs/.prettierignore
- configs/rollup.config.js
- package-lock.json
- packages/react-strict-dom/package.json
- packages/react-strict-dom/tests/benchmarks/benchmarks.node.js
- packages/react-strict-dom/tests/benchmarks/react-native.js
These benchmarks are based on those in styleq, which were used to improve the performance of the StyleX runtime 5-8x. We currently track the performance of `css.create` and `css.props` calls.
> Add Node.js benchmarks for native

- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/useStyleTransition.js
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/src/native/stylex/parseTransform.js
- packages/react-strict-dom/src/types/styles.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
- packages/react-strict-dom/tests/html-test.native.js
For simplicity (and to fix an internal edge case), we now translate all 'transform' values to the React Native object syntax. If a string 'transform' is ever passed to an Animated component, the animation will now work as expected.
Close #123
> Fix `transform` style processing for native

- packages/react-strict-dom/tests/benchmarks/benchmarks.node.js
This will help catch potential future regressions related to the cost of `console` messages in prod.
> Add benchmark for unsupported styles on native

- configs/rollup.config.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/useStrictDOMElement.js
- packages/react-strict-dom/src/native/modules/useStyleTransition.js
- packages/react-strict-dom/src/native/stylex/CSSLengthUnitValue.js
- packages/react-strict-dom/src/native/stylex/CSSTextShadow.js
- packages/react-strict-dom/src/native/stylex/customProperties.js
- packages/react-strict-dom/src/native/stylex/fixContentBox.js
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/src/native/stylex/typed-om/CSSUnparsedValue.js
Wraps the log utils in `__DEV__` on native, so React Native can DCE the log messages in prod builds.
Makes sure that the benchmark build strips code wrapped in `__DEV__`, so we can see the impact of removing logs when processing unsupported props or styles that would otherwise log messages in dev.
> Remove console messages from prod builds

- packages/react-strict-dom/package.json
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/extractStyleThemes.js
- packages/react-strict-dom/src/native/modules/useStyleProps.js
- packages/react-strict-dom/src/native/stylex/SpreadOptions.js
- packages/react-strict-dom/src/native/stylex/customProperties.js
- packages/react-strict-dom/src/native/stylex/index.js
The customProperties map can get very large, and creating copies every render can lead to avoidable GC. This diff removes most places where copies are being made.
> Avoid creating copies of customProperties in native polyfill

- apps/examples/src/tokens.stylex.js
- packages/react-strict-dom/src/native/stylex/customProperties.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/css-test.native.js
The color token values have the following structure:
```tsx
"positive": {
"default": "#31A24C",
"@media (prefers-color-scheme: dark)": "#31A24C"
},
```
However, `resolveVariableReferenceValue` function only support `string` type. All other value types falls to the else statement and returned as-it-is. Currently, This leads to the `color` value to be of the type `[Object object]`, which cannot be parsed by CSS.
With this simple change, we handle the case when the `variableValue` is an object, and return the default value.
TODO: Still need to return dark-theme through media queries `@media (prefers-color-scheme: dark)`.
> Add support for default color token values from DSP

- packages/react-strict-dom/src/shared/logUtils.js
Reduce repeated messages in the logs so there is only one warning or error for each type of issue. In the test environment, every instance is still logged.
> Avoid duplicate console messages

- packages/react-strict-dom/src/native/modules/ContextCustomProperties.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/extractStyleThemes.js
- packages/react-strict-dom/src/native/modules/useStyleProps.js
- packages/react-strict-dom/src/native/stylex/customProperties.js
- packages/react-strict-dom/src/native/stylex/flattenStyleXStyles.js
- packages/react-strict-dom/src/native/stylex/index.js
Simplifies the resolving logic so the concept of "inherited" custom properties isn't exposed beyond the React code. Any time there are custom properties from themes, we have to create a new object for that component during render - this object can be passed to the style resolving functions too.
> Simplify resolving of custom property values

- packages/react-strict-dom/package.json
This change was suggested by the React Native team to better approximate Hermes (no JIT).
> RSD benchmarks with --jitless

- packages/react-strict-dom/benchmarks/fixtures.js
Add a few more values that get parsed and polyfilled so any changes to how they are processed would show up in future benchmark runs.
> Add more polyfills to benchmarks fixtures

- apps/examples/src/App.js
- apps/examples/src/tokens.stylex.js
- packages/react-strict-dom/src/native/modules/ContextCustomProperties.js
- packages/react-strict-dom/src/native/modules/ContextInheritedStyles.js
- packages/react-strict-dom/src/native/modules/TextString.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/extractStyleThemes.js
- packages/react-strict-dom/src/native/modules/useStyleProps.js
- packages/react-strict-dom/src/native/stylex/customProperties.js
- packages/react-strict-dom/src/native/stylex/fixContentBox.js
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/src/types/styles.js
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
- packages/react-strict-dom/tests/html-test.native.js
This patch fixes a source of crashes in React Native and other bugs in the style resolving logic.
1. Previously, the automatic wrapping of raw text strings with `<Text>` didn't fully resolve inherited styles containing StyleX theme variables. Passing objects as style values to React Native  was responsible for the crash.
2. `customProperties` should have values typed `mixed`, since the value can be an object returned from `css.defineVars` when a dark theme Media Query is used in the variable definition.
3. `extractStyleThemes` was only extracting variable values of string type, which excluded numeric and object value theme overrides.
4. `lineHeight` was incorrectly resolved when wrapping raw text strings in a `<Text>`, because the computed `fontSize` could end up being excluded from the …
> Fix string auto-wrap hack with style inheritance of themes

- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/src/native/stylex/isAllowedStyleKey.js
- packages/react-strict-dom/tests/__mocks__/react-native.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/css-test.native.js
- packages/react-strict-dom/tools/rollup/mock-react-native-for-benchmarks.js
Include experimental boxShadow, filter, and mixBlendMode features. This requires React Native version detection.
> Add support for experimental React Native style implementations

- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/useStyleTransition.js
- packages/react-strict-dom/tests/html-test.native.js
The native polyfill for CSS transitions should not setup Animated calls unless transitions are defined.
> Skip animation setup if no style transitions

- packages/react-strict-dom/src/native/modules/ContextInheritedStyles.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/useStyleTransition.js
- packages/react-strict-dom/tests/html-test.native.js
This patch fixes an issue where 'em' units weren't correctly resolved on non-text elements with a 'fontSize'. The component creator was not forwarding 'fontSize' to the style resolver, which mean 'em' units were falling back to using the default 'fontSize' of 16px.
Now the non-text elements only strip text styles after the styles have been fully resolved. This also simplifies the logic for the inherited styles context.
> Fix style inheritance logic in component creator

- packages/react-strict-dom/src/native/modules/TextString.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/resolveUnitlessLineHeight.js
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/html-test.native.js
Make sure the computed lineHeight is inherited, unless it's a unitless value which should act as a fontSize multiplier.
> Fix inheritance of em-based lineHeight

- apps/examples/babel.config.js
- packages/react-strict-dom/README.md
- packages/react-strict-dom/babel.js
- packages/react-strict-dom/tests/__snapshots__/babel-test.js.snap-dom
- packages/react-strict-dom/tests/babel-test.js
Adding 'debug:true' to the plugin options will display sourceMap info in the DOM about the filename and line number responsible for rendering an RSD element.
> Add babel sourceMap info to transform

- .github/workflows/benchmarks.yml
- apps/examples/src/App.js
- packages/benchmarks/compare.js
- packages/benchmarks/perf/mocks/react-native.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/useStyleProps.js
- packages/react-strict-dom/src/native/modules/useStyleTransition.js
- packages/react-strict-dom/src/types/react-native.js
- packages/react-strict-dom/tests/__mocks__/react-native/index.js
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
- packages/react-strict-dom/tests/html-test.native.js
Adds support for CSS transitions when an element doesn't include transitions in the initial state. This supports the use case where a mounted component is updated to add CSS transition styles. It should be re-rendered as an Animated component instead of printing an error about not having an initial transition state.
The 'useStyleTransition' hook is also moved out of 'createStrictDOMComponent' and into the 'useStyleProps' hook.
> CSS transition polyfill initial state improvement

- README.md
- apps/examples/src/App.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-native
Use `View` instead of `Text` to polyfill `blockquote`. This element can contain block elements like `p` and is better as a `View`. Plus, in React Native on Android you can't set partial borders on `Text`.
> Fix native <blockquote> polyfill

- apps/examples/src/App.js
- packages/react-strict-dom/src/dom/runtime.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-dom
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-native
Certain elements should be rendering as View but were defaulting to Text.
And on web the list-style reset is applied only to 'ol' and 'ul' elements, to fix an issue where 'li' was no longering inheriting list-style from its ancestor.
> Add missing elements to DOM -> Native mapping

- packages/react-strict-dom/COMPATIBILITY.md
- packages/react-strict-dom/src/native/stylex/isAllowedStyleKey.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/css-test.native.js
https://github.com/facebook/react-native/pull/45883
> Allow native to use CSS 'isolation'

- packages/benchmarks/perf/mocks/ViewNativeComponent.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-native
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
Bypass the React Native "View" component for "ViewNativeComponent". RSD currently does all the intermediate transforms that View otherwise does in React Native.
> Switches native View to ViewNativeComponent

- packages/benchmarks/perf/mocks/react-native.js
- packages/react-strict-dom/src/native/modules/useStyleProps.js
- packages/react-strict-dom/tests/__mocks__/react-native/index.js
The value of fontScale is available from useWindowDimensions, so PixelRatio is not needed.
> Get fontScale value from useWindowDimensions

- packages/react-strict-dom/src/native/modules/ContextInheritedStyles.js
- packages/react-strict-dom/src/native/modules/__tests__/shallowEqual-test.js
- packages/react-strict-dom/src/native/modules/shallowEqual.js
Optimization to avoid re-renders of html.div with unchanged contexts. Includes full memoization of inherited styles so updates without changes don't force all children to re-render.
> Prevent avoidable re-renders of html.div on native

- packages/benchmarks/package.json
- packages/benchmarks/perf/rollup.config.js
- packages/react-strict-dom/src/native/html.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/createStrictDOMImageComponent.js
- packages/react-strict-dom/src/native/modules/createStrictDOMTextComponent.js
- packages/react-strict-dom/src/native/modules/createStrictDOMTextInputComponent.js
- packages/react-strict-dom/src/native/modules/useNativeProps.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/css-test.native.js
- packages/react-strict-dom/tools/babel.config.js
- packages/react-strict-dom/tools/rollup.config.js
Break up 'createStrictDOMComponent' into separate functions for different types of React Native component. This can help to reduce the amount of unused logic and hooks needed by each type of native component.
> Separate logic for specific native components

- apps/examples/src/App.js
- packages/benchmarks/perf/mocks/TextAncestorContext.js
- packages/benchmarks/perf/rollup.config.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/react-native/TextAncestorContext.js
- packages/react-strict-dom/src/native/react-native/ViewNativeComponent.js
- packages/react-strict-dom/tests/__mocks__/react-native/Libraries/Text/TextAncestor.js
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-native
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
Follow up for 18c5b29 which was reverted in 15f2f00 because TextAncestor context was not incorporated. This patch includes TextAncestorContext and an e2e example to help catch potential future regressions.
> Replace native View with ViewNativeComponent

- packages/react-strict-dom/src/native/stylex/parseTransform.js
- packages/react-strict-dom/src/types/react-native.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/css-test.native.js
The original implementation of `parseTransform` was written before React Native supported `%` units for translations, and assumed that only `px` values are allowed.
> Fix support for % translate transforms

- .eslintrc
- apps/examples/babel.config.js
- apps/examples/metro.config.js
- apps/examples/src/App.js
- apps/examples/src/tokens.stylex.js
- apps/website/src/pages/index.js
- package.json
- packages/react-strict-dom/babel/index.js
- packages/react-strict-dom/package.json
- packages/react-strict-dom/src/dom/index.js
- packages/react-strict-dom/src/dom/runtime.js
- packages/react-strict-dom/src/native/index.js
- packages/react-strict-dom/tests/__snapshots__/babel-test.node.js.snap-node
- packages/react-strict-dom/tests/babel-test.node.js
- patches/@stylexjs+babel-plugin+0.7.5.patch
- patches/@stylexjs+shared+0.7.5.patch
- patches/@stylexjs+stylex+0.7.5.patch
This patch changes RSD to export a babel preset (not plugin), which integrates StyleX to simplify developer setup and ensure that the correct configuration is used.
StyleX itself is also patched to fix theming on web and remove deprecated or unrelated APIs for cross-platform React.
> Babel preset with integrated StyleX

- packages/react-strict-dom/src/native/modules/useStyleTransition.js
- packages/react-strict-dom/tests/__mocks__/react-native/index.js
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
- packages/react-strict-dom/tests/html-test.native.js
Fix #207
This diff updates the `useStyleTransition` hook to utilize the hook equivalent of the"getDerivedStateFromProps" pattern — which ultimately means to "set state" in render instead of writting/reading refs during render.
The only annoying part of this change is needing to do a deep comparison of the style objects since their identies are almost guaranteed to change every render. I've mitigated the performance implications of this by only comparing the style properties which are designated by `transitionProperties`. This does create some limitations in terms of how close we can get to exactly the browser's behaviro wrt CSS transitions but in my testing that limitation was already present before my changes so at least it isn't a regression.
This strategy also inherently provided some …
> Remove ref reads during render in CSS transition polyfill

- .flowconfig
- package-lock.json
- package.json
- packages/scripts/package.json
This PR bumps flow and related tools in the repo to prepare for moving away from `React.AbstractComponent` in favor of the new [component types](https://flow.org/en/docs/react/component-types/).
> Bump flow and related tools

- packages/react-strict-dom/src/dom/html.js
- packages/react-strict-dom/src/native/html.js
In order to adopt react 19's ref-as-prop model, we need to eliminate all the places where they are treated differently. `React.AbstractComponent` is the worst example of this, and we need to eliminate it.
This PR replaces all of them in react-strict-dom's html.js file with the new [component types](https://flow.org/en/docs/react/component-types/).
> Replace `React.AbstractComponent` with component type

- packages/react-strict-dom/src/dom/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/createStrictDOMTextComponent.js
- packages/react-strict-dom/src/native/modules/useNativeProps.js
- packages/react-strict-dom/src/native/modules/useStyleProps.js
- packages/react-strict-dom/src/native/modules/useStyleTransition.js
- packages/react-strict-dom/src/native/stylex/fixContentBox.js
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/src/native/stylex/parseTransform.js
- packages/react-strict-dom/src/types/StrictProps.js
- packages/react-strict-dom/src/types/renderer.native.js
- packages/react-strict-dom/src/types/renderer.web.js
Separate the platform-specific types into `*.native` and `*.web` files. This helps generate libdefs that type check correctly in different environments.
> Disentangle platform-specific flow types

- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
The web's default value for alignContent is 'stetch', whereas in React Native it is 'flex-start'. This patch aligns native with the web.
> Fix default value of alignContent on native

- packages/react-strict-dom/src/native/stylex/index.js
Replace inline regular expression used for capturing CSS custom property names.
> Extract regular expression into constant

- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/createStrictDOMTextComponent.js
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-dom
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-native
- packages/react-strict-dom/tests/html-test.js
Adds default `role` values for certain tags on native
> Add default accessibility roles to native elements

- packages/react-strict-dom/src/native/modules/createStrictDOMTextComponent.js
- packages/react-strict-dom/tests/__snapshots__/compat-test.native.js.snap-native
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-native
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
> Only set userSelect:auto on anchor tags (native)

- apps/website/docs/api/02-css/index.md
- apps/website/docs/contribute/01-development/04-author-patch.md
- apps/website/docs/contribute/02-technicals/01-design-goals.md
- apps/website/docs/contribute/02-technicals/04-tests.md
Fix typo in [Contribute](https://facebook.github.io/react-strict-dom/contribute/) docs,
The last 5 commits from `HEAD` would translate to `HEAD~5`.  
`HEAD^5` would mean **_5th parent of HEAD_** (octopus merge commit) which seems to be not the intent here.
> Fix typo in Docs

- apps/examples/package.json
- apps/examples/postcss.config.js
- apps/website/docs/learn/01-installation.md
- apps/website/docs/learn/02-environment-setup.md
- package-lock.json
- packages/react-strict-dom/package.json
- packages/react-strict-dom/postcss/plugin.js
https://github.com/facebook/react-strict-dom/issues/281#issuecomment-2712591645
This PR upstreams [postcss-react-strict-dom](https://github.com/javascripter/postcss-react-strict-dom) to the official repo to make it easier for maintainers to make changes.
I added RSD compatibility to `@stylexjs/postcss-plugin` in [this PR](https://github.com/facebook/stylex/pull/1063), so this adds `react-strict-dom/postcss-plugin` that re-exports the StyleX PostCSS Plugin with the required configuration for RSD consumers.
- Added PostCSS Plugin to `packages/react-strict-dom/postcss/plugin.js`
- Export the plugin as `react-strict-dom/postcss-plugin` in package.json
- Updated `apps/examples` to use the official plugin and removed postcss-react-strict-dom dependency
- Updated docs to use the official plugin …
> Add react-strict-dom/postcss-plugin based on @stylexjs/postcss-plugin

- packages/react-strict-dom/package.json
v0.0.38 published to npm does not include `postcss/plugin.js` due to missing package.json `files` field.
https://github.com/facebook/react-strict-dom/pull/308 added postcss exports but did not include the actual `postcss/plugin.js` files, causing the files to be not included when publishing to npm.
Adds `"postcss/*"` to `files` field similar to `babel` preset files.
> Add missing postcss files in package.json `files` field

- apps/website/docs/api/03-html/09-option.md
- apps/website/docs/api/03-html/10-select.md
- packages/react-strict-dom/src/types/StrictReactDOMOptionProps.js
- packages/react-strict-dom/src/types/StrictReactDOMSelectProps.js
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-dom
- packages/react-strict-dom/tests/html-test.js
Unlike in HTML, passing a `selected` attribute to `<option>` is not supported. Instead, the selected option's value should be passed to the`value` or `defaultValue` props of the `<select>` element.
Fix #335
> Fix props for `<select>` and `<option>` elements

- apps/website/docs/api/02-css/index.md
- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/src/native/stylex/isAllowedStyleKey.js
- packages/react-strict-dom/tests/__snapshots__/css-test.native.js.snap-native
- packages/react-strict-dom/tests/css-test.native.js
Delegate `backgroundImage` to `experimental_backgroundImage` in React Native. This should provide support for using linear and radial gradients.
> Add support for CSS `backgroundImage` gradients on native

- packages/react-strict-dom/src/native/stylex/index.js
- packages/react-strict-dom/tests/css-test.native.js
Print an error message if flex properties are used on native without the required "display:flex" style. This should help prevent layout divergence between native and web for native-first development.
> Add flexbox error logging for native

- packages/react-strict-dom/src/native/stylex/typed-om/CSSUnparsedValue.js
- packages/react-strict-dom/src/native/stylex/typed-om/CSSVariableReferenceValue.js
* Avoid calling `super()` on native.
* Avoid private class fields.
This change was tested e2e using React Native Fantom. The test case was rendering 100 `html.div` elements with various props and the "complex" styles fixture used in this repo's [JS benchmarks](https://github.com/facebook/react-strict-dom/blob/main/packages/benchmarks/perf/tests/css-props-tests.js). Results as follows...
| Test Scenario | Metric | Main | Optimized | % Change |
|---------------|--------|------|-----------|----------|
| **Nested divs** | Latency Avg (ns) | 29,839,920 | 28,962,893 | -2.94% |
| | Latency Median (ns) | 29,454,631 | 28,908,837 | -1.85% |
| | Throughput Avg (ops/s) | 34 | 35 | +2.94% |
| | Throughput Median (ops/s) | 34 | 35 | +2.94% |
| **Sibling divs** | Latency Avg (ns) | 29,703,416 | …
> Make optimizations to native entrypoint for Hermes

- packages/react-strict-dom/src/native/modules/useStrictDOMElement.js
- packages/react-strict-dom/tests/html-test.native.js
I hadn't realised this got called multiple times with the same node and it isn't currently idempotent so each time a component re-renders it re-wraps getBoundingClientRect, increasing the amount the returned rect is scaled by each time.
Issue is only present if viewportScale !== 1
Fix captures the original getBoundingClientRect in a WeakMap so subsequent calls will re-use the original function when wrapping
> Make elementCallback idempotent if using a custom viewport width

- packages/react-strict-dom/src/native/stylex/typed-om/CSSUnparsedValue.js
- packages/react-strict-dom/src/types/value-parser.js
- tools/flow-typed/npm/postcss-value-parser_vx.x.x.js
Don't declare global types in the `flow-typed` libdef for `postcss-value-parser`, this replicates the fbsource Flow error. Add a types file that can be included in the build to avoid errors for missing type definitions. These definitions are required now that `CSSUnparsedValue` doesn't use private fields and the types appear in the build artefacts.
@martinbooth I tried syncing this branch and it resolved the flow errors.
> Fix postcss-value-parser flow types

- packages/react-strict-dom/src/native/modules/ContextCustomProperties.js
Prevent unnecessary object creation and merging when dependencies haven't changed.
| Task | Metric | Before | After | Difference | % Change |
|------|--------|--------|-------|------------|----------|
| **Nested divs** | Latency avg (ns) | 30,296,619.98 | 28,857,194.77 | -1,439,425.21 | -4.75% |
|  | Latency median (ns) | 29,549,489.50 | 28,850,770.50 | -698,719.00 | -2.36% |
|  | Throughput avg (ops/s) | 33 | 35 | +2 | +6.06% |
|  | Throughput median (ops/s) | 34 | 35 | +1 | +2.94% |
| **Sibling divs** | Latency avg (ns) | 29,540,653.28 | 29,049,781.09 | -490,872.19 | -1.66% |
|  | Latency median (ns) | 29,401,702.50 | 29,080,871.50 | -320,831.00 | -1.09% |
|  | Throughput avg (ops/s) | 34 | 34 | 0 | 0.00% |
|  | Throughput median (ops/s) | 34 | 34 | 0 | 0.00% |
| (index) | Task name …
> Optimize useCustomProperties on native

- packages/react-strict-dom/src/native/css/processStyle.js
- packages/react-strict-dom/src/native/modules/useStyleProps.js
| Task | Metric | Before | After | Difference | % Change |
|------|--------|--------|-------|------------|----------|
| **Nested divs** | Latency avg (ns) | 30,725,126.06 | 27,848,582.47 | -2,876,543.59 | -9.36% |
| | Latency median (ns) | 30,348,498.00 | 27,827,932.50 | -2,520,565.50 | -8.30% |
| | Throughput avg (ops/s) | 33 | 36 | +3 | +9.09% |
| | Throughput median (ops/s) | 33 | 36 | +3 | +9.09% |
| **Sibling divs** | Latency avg (ns) | 30,095,190.50 | 27,493,222.28 | -2,601,968.22 | -8.65% |
| | Latency median (ns) | 29,846,615.00 | 27,508,688.00 | -2,337,927.00 | -7.83% |
| | Throughput avg (ops/s) | 33 | 36 | +3 | +9.09% |
| | Throughput median (ops/s) | 34 | 36 | +2 | +5.88% |
| (index) | Task name                                                             | Latency average (ns) …
> Native performance optimizations

- packages/react-strict-dom/src/native/modules/useStrictDOMElement.js
- packages/react-strict-dom/tests/__snapshots__/compat-test.native.js.snap-native
- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-native
- packages/react-strict-dom/tests/__snapshots__/html-test.native.js.snap-native
- packages/react-strict-dom/tests/html-test.native.js
We shouldn't create an object if the underlying node is null, as this handle is meant to emulate the node but can't proxy methods if none exist.
> Go back to using ref callback instead of useImperativeHandle

- apps/website/docs/learn/environment-setup/01-expo.md
- apps/website/docs/learn/environment-setup/02-next.md
- apps/website/docs/learn/environment-setup/_category_.yml
Modified version of #343
* Creates separate Expo/Next docs pages.
* Incorporates feedback on #343 
cc @MoOx @javascripter
> Add Next.js setup instructions to docs

- packages/react-strict-dom/src/native/css/index.js
- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/src/native/modules/useNativeProps.js
- packages/react-strict-dom/tests/css-test.native.js
- packages/react-strict-dom/tests/html-test.native.js
These messages will help developers on native to know when styles will have no effect on web because they only work on flex children, but the parent is not a flex container. On native, the styles will work because all elements are `display:flex`, but this is not the case on web.
The messages are based on those provided by Chrome DevTools
> Add error messages for styles that only work on flex children

- packages/react-strict-dom/src/native/compat.js
- packages/react-strict-dom/tests/__snapshots__/compat-test.native.js.snap-native
- packages/react-strict-dom/tests/compat-test.native.js
This prop previously mixed the semantics of web and native in the accepted values. Now the values match the tag names on web, and indicate the equivalent `html.*` functional role that the compat.native component performs. LLMs have a better success rate using this API after this change. So it was likely somewhat confusing for people too.
> Change the accepted values of `<compat.native>` prop `as`

- packages/react-strict-dom/tests/__snapshots__/html-test.js.snap-dom
- packages/react-strict-dom/tools/jest/babelConfig.js
- packages/react-strict-dom/tools/rollup/babelConfig.mjs
Target React 19 runtime so we avoid the forwardRef wrapper and props object copying overhead.
What the component syntax compiles to now
> Configure hermes parser not to output fowardRef wrapper

- packages/react-strict-dom/src/native/modules/useStrictDOMElement.js
- packages/react-strict-dom/tests/html-test.native.js
- packages/website/docs/api/03-html/index.md
Forwards all the other supported APIs, like DOM traversal
> Copy DOM APIs from native node to strict ref

- packages/react-strict-dom/src/native/modules/createStrictDOMComponent.js
- packages/react-strict-dom/tests/html-test.native.js
Flex items are inherently positioned for zIndex. Unlike other elements, flex items (direct children of a flex container) can utilize zIndex to control their stacking order without explicitly setting a position value other than static.
> Fix native zIndex error condition

- package-lock.json
- packages/postcss-react-strict-dom/package.json
- packages/react-strict-dom/package.json
Update StyleX packages to 0.15.4.
Resolves an issue with the postcss plugin expecting a newer function signature: #401
> Update StyleX packages to 0.15.4

- packages/website/docs/api/02-css/01-create.md
- packages/website/docs/learn/01-installation.md
- packages/website/docusaurus.config.js
- packages/website/static/llms.txt
Add an initial LLM context to help bootstrap LLM-based development. We've had success with this approach internally
> Add llms.txt to docs
